const serviceTypes = {
	START_FETCH_SINGLE_SERVICES: 'START_FETCH_SINGLE_SERVICES',
	SUCCESS_FETCH_SINGLE_SERVICES: 'SUCCESS_FETCH_SINGLE_SERVICES',
	FAIL_FETCH_SINGLE_SERVICES: 'FAIL_FETCH_SINGLE_SERVICES',
}

export default serviceTypes